---
- name: test if tigervnc_username is set correctly
  assert:
    that:
      - tigervnc_username is defined
      - tigervnc_username | length > 0

- name: test if tigervnc_groupname is set correctly
  assert:
    that:
      - tigervnc_groupname is defined
      - tigervnc_groupname | length > 0

- name: test if tigervnc_password is set correctly
  assert:
    that:
      - tigervnc_password is defined
      - tigervnc_password | length > 0

- name: test if tigervnc_user_exists is set correctly
  assert:
    that:
      - tigervnc_user_exists is defined
      - tigervnc_user_exists | type_debug == "bool"

- name: test if tigervnc_desktop_session is set correctly
  assert:
    that:
      - tigervnc_desktop_session is defined
      - tigervnc_desktop_session | length > 0
